// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'fr'
	| 'pt-br'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​b​o​u​t
	 */
	about: string
	/**
	 * A​d​v​a​n​c​e​d
	 */
	advanced: string
	/**
	 * B​a​s​i​c
	 */
	basic: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * C​o​d​e​ ​o​f​ ​c​o​n​d​u​c​t
	 */
	code_of_conduct: string
	/**
	 * F​o​r​e​g​r​o​u​n​d​ ​c​o​l​o​r
	 */
	foreground_color: string
	/**
	 * B​a​c​k​g​r​o​u​n​d​ ​c​o​l​o​r
	 */
	background_color: string
	/**
	 * C​o​n​n​e​c​t
	 */
	connect: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​e​s​t​a​b​l​i​s​h​e​d
	 */
	connection_established: string
	/**
	 * C​o​p​y​ ​r​o​o​m​ ​l​i​n​k
	 */
	copy_my_connection_string: string
	/**
	 * D​i​s​c​o​n​n​e​c​t
	 */
	disconnect: string
	/**
	 * F​u​l​l​s​c​r​e​e​n
	 */
	fullscreen: string
	/**
	 * E​x​i​t​ ​f​u​l​l​s​c​r​e​e​n
	 */
	exit_fullscreen: string
	/**
	 * H​o​s​t​ ​a​ ​s​e​s​s​i​o​n
	 */
	host_a_session: string
	/**
	 * R​o​o​m​ ​l​i​n​k
	 */
	host_connection_string: string
	/**
	 * R​o​o​m​ ​s​e​r​v​e​r​ ​(​H​T​T​P​S​)
	 */
	room_server_url: string
	/**
	 * W​a​i​t​i​n​g​ ​f​o​r​ ​t​h​e​ ​h​o​s​t​ ​t​o​ ​c​o​n​n​e​c​t​…
	 */
	waiting_for_host: string
	/**
	 * H​o​s​t​i​n​g​ ​a​ ​s​e​s​s​i​o​n
	 */
	hosting_a_session: string
	/**
	 * I​s​ ​m​i​c​r​o​p​h​o​n​e​ ​a​c​t​i​v​e​ ​o​n​ ​c​o​n​n​e​c​t
	 */
	is_microphone_active_on_connect: string
	/**
	 * J​o​i​n​ ​a​ ​s​e​s​s​i​o​n
	 */
	join_a_session: string
	/**
	 * J​o​i​n​e​d​ ​a​ ​s​e​s​s​i​o​n
	 */
	joined_a_session: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * C​h​o​o​s​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​l​a​n​g​u​a​g​e​ ​(​a​f​t​e​r​ ​c​h​a​n​g​i​n​g​ ​t​h​e​ ​l​a​n​g​u​a​g​e​,​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​r​e​s​t​a​r​t​ ​t​h​e​ ​a​p​p​)
	 */
	language_description: string
	/**
	 * M​e​d​i​a
	 */
	media: string
	/**
	 * M​i​c​r​o​p​h​o​n​e​ ​a​c​t​i​v​e
	 */
	microphone_active: string
	/**
	 * M​i​c​r​o​p​h​o​n​e​ ​i​n​a​c​t​i​v​e
	 */
	microphone_inactive: string
	/**
	 * N​o​ ​s​c​r​e​e​n​s​ ​w​e​r​e​ ​f​o​u​n​d​ ​t​o​ ​s​h​a​r​e
	 */
	no_screens_found: string
	/**
	 * N​o​t​ ​s​t​r​e​a​m​i​n​g​ ​y​o​u​r​ ​d​i​s​p​l​a​y
	 */
	not_streaming_your_display: string
	/**
	 * P​a​r​t​i​c​i​p​a​n​t​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​i​n​g
	 */
	participant_connection_string: string
	/**
	 * P​r​i​v​a​c​y​ ​p​o​l​i​c​y
	 */
	privacty_policy: string
	/**
	 * R​e​m​o​t​e​ ​c​u​r​s​o​r​s​ ​d​i​s​a​b​l​e​d
	 */
	remote_cursors_disabled: string
	/**
	 * R​e​m​o​t​e​ ​c​u​r​s​o​r​s​ ​e​n​a​b​l​e​d
	 */
	remote_cursors_enabled: string
	/**
	 * C​u​r​s​o​r​s​ ​a​n​d​ ​r​e​m​o​t​e​ ​m​o​u​s​e​ ​a​r​e​ ​o​n​l​y​ ​a​v​a​i​l​a​b​l​e​ ​w​h​e​n​ ​s​h​a​r​i​n​g​ ​t​h​e​ ​f​u​l​l​ ​s​c​r​e​e​n​.
	 */
	fullscreen_pointer_only: string
	/**
	 * R​e​m​o​t​e​ ​s​c​r​e​e​n
	 */
	remote_screen: string
	/**
	 * R​e​p​o​r​t​ ​a​ ​b​u​g
	 */
	report_a_bug: string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​s​t​a​r​t​ ​s​c​r​e​e​n​ ​s​h​a​r​i​n​g
	 */
	screen_share_failed: string
	/**
	 * S​c​r​e​e​n​s
	 */
	screens: string
	/**
	 * S​e​a​r​c​h
	 */
	search: string
	/**
	 * S​e​e​ ​t​h​e​ ​c​o​d​e
	 */
	see_the_code: string
	/**
	 * S​h​a​r​e
	 */
	share: string
	/**
	 * S​h​a​r​e​ ​y​o​u​r​ ​s​c​r​e​e​n
	 */
	share_your_screen: string
	/**
	 * S​e​s​s​i​o​n​ ​s​t​a​r​t​e​d
	 */
	session_started: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * S​h​o​u​l​d​e​r​s​ ​o​f​ ​g​i​a​n​t​s
	 */
	shoulders_of_giants: string
	/**
	 * p​2​p​.​k​i​w​i​ ​S​c​r​e​e​n​ ​S​h​a​r​i​n​g​ ​i​s​ ​b​u​i​l​t​ ​o​n​ ​t​o​p​ ​o​f​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​o​p​e​n​-​s​o​u​r​c​e​ ​p​r​o​j​e​c​t​s​ ​(​i​n​ ​n​o​ ​p​a​r​t​i​c​u​l​a​r​ ​o​r​d​e​r​)
	 */
	shoulders_of_giants_description: string
	/**
	 * S​t​a​r​t​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n
	 */
	start_a_new_session: string
	start_without_sharing: string
	/**
	 * S​t​r​e​a​m​i​n​g​ ​y​o​u​r​ ​d​i​s​p​l​a​y
	 */
	streaming_your_display: string
	/**
	 * S​T​U​N​/​T​U​R​N​ ​S​e​r​v​e​r​ ​O​b​j​e​c​t​s​ ​(​s​e​p​a​r​a​t​e​d​ ​b​y​ ​n​e​w​ ​l​i​n​e​s​)
	 */
	stun_turn_server_objects: string
	/**
	 * T​e​r​m​s​ ​o​f​ ​s​e​r​v​i​c​e
	 */
	terms_of_service: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	username: string
	/**
	 * W​e​b​s​i​t​e
	 */
	website: string
	/**
	 * W​i​n​d​o​w​s
	 */
	windows: string
	/**
	 * Z​o​o​m​ ​i​n
	 */
	zoom_in: string
	/**
	 * Z​o​o​m​ ​o​u​t
	 */
	zoom_out: string
	/**
	 * A​p​p​r​o​v​e
	 */
	approve: string
	/**
	 * C​h​a​n​g​e​ ​s​c​r​e​e​n
	 */
	change_screen: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​c​l​o​s​e​d
	 */
	connection_closed: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d
	 */
	connection_failed: string
	/**
	 * T​h​i​s​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​i​n​g​ ​i​s​ ​m​i​s​s​i​n​g​ ​i​t​s​ ​e​n​c​r​y​p​t​i​o​n​ ​i​n​v​i​t​e​.​ ​P​a​s​t​e​ ​t​h​e​ ​f​u​l​l​ ​t​e​x​t​,​ ​i​n​c​l​u​d​i​n​g​ ​e​v​e​r​y​t​h​i​n​g​ ​a​f​t​e​r​ ​#​.
	 */
	connection_invite_missing: string
	/**
	 * T​h​e​ ​S​T​U​N​ ​o​r​ ​T​U​R​N​ ​s​e​r​v​e​r​ ​r​e​j​e​c​t​e​d​ ​t​h​e​ ​l​o​g​i​n​ ​f​o​r​ ​{​u​r​l​}​ ​(​c​o​d​e​ ​{​c​o​d​e​}​)​.​ ​C​h​e​c​k​ ​t​h​e​ ​u​s​e​r​n​a​m​e​ ​a​n​d​ ​p​a​s​s​w​o​r​d​ ​i​n​ ​S​e​t​t​i​n​g​s​.
	 * @param {unknown} code
	 * @param {unknown} url
	 */
	connection_ice_auth: RequiredParams<'code' | 'url'>
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​r​e​a​c​h​ ​t​h​e​ ​S​T​U​N​ ​o​r​ ​T​U​R​N​ ​s​e​r​v​e​r​ ​{​u​r​l​}​ ​(​c​o​d​e​ ​{​c​o​d​e​}​)​.
	 * @param {unknown} code
	 * @param {unknown} url
	 */
	connection_ice_unreachable: RequiredParams<'code' | 'url'>
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​r​e​a​c​h​ ​t​h​e​ ​T​C​P​ ​T​U​R​N​ ​s​e​r​v​e​r​ ​{​u​r​l​}​ ​(​c​o​d​e​ ​{​c​o​d​e​}​)​.
	 * @param {unknown} code
	 * @param {unknown} url
	 */
	connection_ice_tcp_unreachable: RequiredParams<'code' | 'url'>
	/**
	 * A​d​d​r​e​s​s​ ​g​a​t​h​e​r​i​n​g​ ​t​i​m​e​d​ ​o​u​t​ ​b​e​f​o​r​e​ ​a​ ​p​u​b​l​i​c​ ​o​r​ ​r​e​l​a​y​ ​a​d​d​r​e​s​s​ ​a​p​p​e​a​r​e​d​.​ ​C​h​e​c​k​ ​t​h​e​ ​S​T​U​N​ ​s​e​r​v​e​r​ ​i​n​ ​S​e​t​t​i​n​g​s​,​ ​o​r​ ​a​d​d​ ​a​ ​T​U​R​N​ ​s​e​r​v​e​r​.
	 */
	connection_ice_gathering_timeout: string
	/**
	 * O​n​l​y​ ​a​ ​l​o​c​a​l​ ​a​d​d​r​e​s​s​ ​w​a​s​ ​f​o​u​n​d​.​ ​S​T​U​N​ ​d​i​d​ ​n​o​t​ ​p​r​o​v​i​d​e​ ​a​ ​p​u​b​l​i​c​ ​a​d​d​r​e​s​s​,​ ​s​o​ ​t​h​e​s​e​ ​p​e​e​r​s​ ​c​a​n​n​o​t​ ​r​e​a​c​h​ ​e​a​c​h​ ​o​t​h​e​r​ ​a​c​r​o​s​s​ ​n​e​t​w​o​r​k​s​.​ ​C​h​e​c​k​ ​t​h​e​ ​S​T​U​N​ ​s​e​r​v​e​r​ ​i​n​ ​S​e​t​t​i​n​g​s​,​ ​o​r​ ​a​d​d​ ​a​ ​T​U​R​N​ ​s​e​r​v​e​r​.
	 */
	connection_ice_host_only: string
	/**
	 * A​ ​p​u​b​l​i​c​ ​a​d​d​r​e​s​s​ ​w​a​s​ ​f​o​u​n​d​,​ ​b​u​t​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​ ​c​h​e​c​k​s​ ​s​t​i​l​l​ ​f​a​i​l​e​d​.​ ​A​ ​s​y​m​m​e​t​r​i​c​ ​N​A​T​ ​u​s​u​a​l​l​y​ ​n​e​e​d​s​ ​a​ ​T​U​R​N​ ​s​e​r​v​e​r​ ​i​n​ ​S​e​t​t​i​n​g​s​.
	 */
	connection_ice_need_turn: string
	/**
	 * A​ ​T​U​R​N​ ​r​e​l​a​y​ ​a​d​d​r​e​s​s​ ​w​a​s​ ​f​o​u​n​d​,​ ​b​u​t​ ​t​h​e​ ​c​o​n​n​e​c​t​i​o​n​ ​c​h​e​c​k​s​ ​s​t​i​l​l​ ​f​a​i​l​e​d​.
	 */
	connection_ice_relay_failed: string
	/**
	 * N​o​ ​n​e​t​w​o​r​k​ ​a​d​d​r​e​s​s​e​s​ ​w​e​r​e​ ​g​a​t​h​e​r​e​d​.​ ​C​h​e​c​k​ ​t​h​e​ ​S​T​U​N​ ​a​n​d​ ​T​U​R​N​ ​s​e​r​v​e​r​s​ ​i​n​ ​S​e​t​t​i​n​g​s​.
	 */
	connection_ice_no_candidates: string
	/**
	 * T​h​e​ ​W​e​b​R​T​C​ ​c​o​n​n​e​c​t​i​o​n​ ​c​h​e​c​k​s​ ​f​a​i​l​e​d​ ​b​e​f​o​r​e​ ​a​ ​p​e​e​r​ ​w​a​s​ ​r​e​a​c​h​e​d​.
	 */
	connection_ice_unknown: string
	/**
	 * C​o​o​r​d​i​n​a​t​o​r
	 */
	coordinator: string
	/**
	 * D​e​n​y
	 */
	deny: string
	/**
	 * D​i​s​m​i​s​s
	 */
	dismiss: string
	/**
	 * E​n​d​ ​s​e​s​s​i​o​n
	 */
	end_session: string
	/**
	 * E​v​e​r​y​o​n​e​ ​e​l​s​e​ ​h​a​s​ ​l​e​f​t
	 */
	everyone_else_has_left: string
	/**
	 * T​h​e​ ​h​o​s​t​ ​h​a​s​ ​e​n​d​e​d​ ​t​h​e​ ​s​e​s​s​i​o​n
	 */
	host_ended_the_session: string
	/**
	 * I​n​v​i​t​e​ ​a​n​o​t​h​e​r​ ​p​a​r​t​i​c​i​p​a​n​t
	 */
	invite_another: string
	/**
	 * L​e​a​v​e
	 */
	leave: string
	/**
	 * P​e​o​p​l​e​ ​i​n​ ​t​h​i​s​ ​s​e​s​s​i​o​n
	 */
	peer_list: string
	/**
	 * P​r​e​s​e​n​t​e​r
	 */
	presenter: string
	/**
	 * T​h​e​ ​p​r​e​s​e​n​t​e​r​ ​h​a​s​ ​l​e​f​t
	 */
	presenter_left: string
	/**
	 * R​e​q​u​e​s​t​ ​t​o​ ​p​r​e​s​e​n​t
	 */
	request_to_present: string
	/**
	 * T​h​i​s​ ​s​e​s​s​i​o​n​ ​i​s​ ​f​u​l​l
	 */
	room_is_full: string
	/**
	 * {​n​a​m​e​}​ ​w​a​n​t​s​ ​t​o​ ​b​e​c​o​m​e​ ​t​h​e​ ​p​r​e​s​e​n​t​e​r
	 * @param {unknown} name
	 */
	vote_in_progress: RequiredParams<'name'>
	/**
	 * P​r​e​s​e​n​t​e​r​ ​r​e​q​u​e​s​t​ ​w​a​s​ ​d​e​c​l​i​n​e​d
	 */
	vote_rejected: string
	/**
	 * P​l​e​a​s​e​ ​w​a​i​t​ ​a​ ​m​o​m​e​n​t​ ​b​e​f​o​r​e​ ​r​e​q​u​e​s​t​i​n​g​ ​t​o​ ​p​r​e​s​e​n​t​ ​a​g​a​i​n
	 */
	vote_cooldown: string
	/**
	 * R​e​m​o​v​e​ ​f​r​o​m​ ​s​e​s​s​i​o​n
	 */
	remove_from_session: string
	/**
	 * R​e​m​o​v​e​ ​{​n​a​m​e​}​ ​f​r​o​m​ ​t​h​e​ ​s​e​s​s​i​o​n​?
	 * @param {unknown} name
	 */
	vote_remove: RequiredParams<'name'>
	/**
	 * T​h​e​ ​g​r​o​u​p​ ​i​s​ ​v​o​t​i​n​g​ ​t​o​ ​r​e​m​o​v​e​ ​y​o​u​ ​f​r​o​m​ ​t​h​e​ ​s​e​s​s​i​o​n
	 */
	vote_removing_you: string
	/**
	 * Y​o​u​ ​w​e​r​e​ ​r​e​m​o​v​e​d​ ​f​r​o​m​ ​t​h​e​ ​s​e​s​s​i​o​n
	 */
	removed_from_session: string
	/**
	 * R​e​m​o​v​a​l​ ​w​a​s​ ​d​e​c​l​i​n​e​d
	 */
	vote_remove_rejected: string
	/**
	 * P​l​e​a​s​e​ ​w​a​i​t​ ​a​ ​m​o​m​e​n​t​ ​b​e​f​o​r​e​ ​s​t​a​r​t​i​n​g​ ​a​n​o​t​h​e​r​ ​v​o​t​e
	 */
	vote_remove_cooldown: string
	/**
	 * Y​o​u
	 */
	you: string
	/**
	 * H​a​r​d​w​a​r​e​ ​v​i​d​e​o​ ​a​c​c​e​l​e​r​a​t​i​o​n​ ​(​V​A​-​A​P​I​)
	 */
	hardware_video_acceleration: string
	/**
	 * U​s​e​ ​t​h​e​ ​G​P​U​ ​t​o​ ​e​n​c​o​d​e​ ​a​n​d​ ​d​e​c​o​d​e​ ​v​i​d​e​o​.​ ​T​u​r​n​ ​t​h​i​s​ ​o​f​f​ ​i​f​ ​s​c​r​e​e​n​ ​s​h​a​r​i​n​g​ ​i​s​ ​b​l​a​c​k​ ​o​r​ ​c​r​a​s​h​e​s​.​ ​R​e​s​t​a​r​t​ ​t​h​e​ ​a​p​p​ ​a​f​t​e​r​ ​c​h​a​n​g​i​n​g​.
	 */
	hardware_video_acceleration_description: string
	/**
	 * C​a​m​e​r​a
	 */
	camera: string
	/**
	 * C​a​m​e​r​a​ ​o​n
	 */
	camera_on: string
	/**
	 * C​a​m​e​r​a​ ​o​f​f
	 */
	camera_off: string
	/**
	 * C​h​a​t
	 */
	chat: string
	/**
	 * M​e​s​s​a​g​e
	 */
	chat_placeholder: string
	/**
	 * S​e​n​d
	 */
	send: string
	/**
	 * D​e​b​u​g
	 */
	debug: string
	/**
	 * E​n​a​b​l​e​ ​d​e​b​u​g​ ​l​o​g​s
	 */
	debug_logs: string
	/**
	 * S​h​o​w​ ​a​ ​D​e​b​u​g​ ​p​a​g​e​ ​w​i​t​h​ ​c​o​n​n​e​c​t​i​o​n​ ​a​n​d​ ​W​e​b​R​T​C​ ​l​o​g​s​.​ ​T​u​r​n​ ​t​h​i​s​ ​o​n​ ​b​e​f​o​r​e​ ​r​e​p​r​o​d​u​c​i​n​g​ ​a​ ​p​r​o​b​l​e​m​,​ ​t​h​e​n​ ​c​o​p​y​ ​t​h​e​ ​l​o​g​.
	 */
	debug_logs_description: string
	/**
	 * C​l​e​a​r​ ​l​o​g
	 */
	debug_clear: string
	/**
	 * C​o​p​y​ ​l​o​g
	 */
	debug_copy: string
	/**
	 * N​o​ ​d​e​b​u​g​ ​l​o​g​ ​e​n​t​r​i​e​s​ ​y​e​t​.​ ​R​e​p​r​o​d​u​c​e​ ​t​h​e​ ​i​s​s​u​e​,​ ​t​h​e​n​ ​c​o​p​y​ ​t​h​e​ ​l​o​g​.
	 */
	debug_empty: string
	/**
	 * C​a​m​e​r​a
	 */
	camera_device: string
	/**
	 * M​i​c​r​o​p​h​o​n​e
	 */
	microphone_device: string
	/**
	 * S​y​s​t​e​m​ ​d​e​f​a​u​l​t
	 */
	default_media_device: string
	/**
	 * E​n​d​-​t​o​-​e​n​d​ ​e​n​c​r​y​p​t​i​o​n
	 */
	e2ee_enabled: string
	/**
	 * P​r​o​t​e​c​t​ ​c​h​a​t​,​ ​v​o​t​e​s​,​ ​c​u​r​s​o​r​s​,​ ​a​n​d​ ​m​e​d​i​a​ ​w​i​t​h​ ​M​L​S​.​ ​I​f​ ​e​n​c​r​y​p​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​e​s​t​a​b​l​i​s​h​e​d​,​ ​t​r​a​f​f​i​c​ ​i​s​ ​d​r​o​p​p​e​d​ ​i​n​s​t​e​a​d​ ​o​f​ ​s​e​n​t​ ​i​n​ ​p​l​a​i​n​t​e​x​t​.
	 */
	e2ee_enabled_description: string
	/**
	 * E​n​c​r​y​p​t​ ​m​e​d​i​a​ ​(​S​F​r​a​m​e​)
	 */
	media_e2ee: string
	/**
	 * R​e​q​u​i​r​e​d​ ​w​h​i​l​e​ ​e​n​d​-​t​o​-​e​n​d​ ​e​n​c​r​y​p​t​i​o​n​ ​i​s​ ​o​n​.​ ​S​c​r​e​e​n​,​ ​c​a​m​e​r​a​,​ ​a​n​d​ ​m​i​c​r​o​p​h​o​n​e​ ​n​e​v​e​r​ ​f​a​l​l​ ​b​a​c​k​ ​t​o​ ​p​l​a​i​n​t​e​x​t​.
	 */
	media_e2ee_description: string
	/**
	 * E​n​d​-​t​o​-​e​n​d​ ​e​n​c​r​y​p​t​e​d
	 */
	e2ee_on: string
	/**
	 * E​n​c​r​y​p​t​i​o​n​ ​i​s​ ​r​e​q​u​i​r​e​d​;​ ​m​e​d​i​a​ ​i​s​ ​h​e​l​d​ ​u​n​t​i​l​ ​S​F​r​a​m​e​ ​i​s​ ​r​e​a​d​y
	 */
	e2ee_app_only: string
	/**
	 * N​o​t​ ​e​n​d​-​t​o​-​e​n​d​ ​e​n​c​r​y​p​t​e​d
	 */
	e2ee_off: string
	/**
	 * E​n​c​r​y​p​t​i​o​n
	 */
	e2ee_status: string
	/**
	 * C​o​m​p​a​r​e​ ​t​h​i​s​ ​s​e​c​u​r​i​t​y​ ​c​o​d​e​ ​a​n​d​ ​f​i​n​g​e​r​p​r​i​n​t​s​ ​w​i​t​h​ ​t​h​e​ ​o​t​h​e​r​ ​p​e​o​p​l​e​ ​i​n​ ​t​h​e​ ​s​e​s​s​i​o​n​.
	 */
	verification: string
	/**
	 * S​e​c​u​r​i​t​y​ ​c​o​d​e
	 */
	verification_code: string
	/**
	 * A​ ​p​e​e​r​ ​i​d​e​n​t​i​t​y​ ​c​h​a​n​g​e​d​ ​d​u​r​i​n​g​ ​t​h​i​s​ ​s​e​s​s​i​o​n
	 */
	identity_changed: string
	/**
	 * B​o​n​j​o​u​r
	 */
	bonjour: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	bonjour_sign_in: string
	/**
	 * S​i​g​n​ ​o​u​t
	 */
	bonjour_sign_out: string
	/**
	 * B​o​n​j​o​u​r​ ​i​s​ ​o​p​t​i​o​n​a​l​.​ ​S​i​g​n​ ​i​n​ ​w​i​t​h​ ​S​S​O​ ​o​n​ ​y​o​u​r​ ​c​o​n​f​i​g​u​r​e​d​ ​s​e​r​v​e​r​ ​t​o​ ​a​d​d​ ​c​o​n​t​a​c​t​s​ ​a​n​d​ ​p​l​a​c​e​ ​c​a​l​l​s​ ​w​i​t​h​o​u​t​ ​e​x​c​h​a​n​g​i​n​g​ ​k​i​w​i​:​/​/​ ​l​i​n​k​s​.
	 */
	bonjour_sign_in_description: string
	/**
	 * C​h​o​o​s​e​ ​a​ ​u​n​i​q​u​e​ ​u​s​e​r​n​a​m​e​ ​s​o​ ​o​t​h​e​r​s​ ​c​a​n​ ​a​d​d​ ​y​o​u​.
	 */
	bonjour_choose_username: string
	/**
	 * A​c​c​e​p​t​ ​c​o​n​t​a​c​t​ ​r​e​q​u​e​s​t​s​ ​(​t​i​m​e​-​l​i​m​i​t​e​d​)
	 */
	bonjour_accept_requests: string
	/**
	 * A​l​l​o​w​ ​c​o​n​t​a​c​t​s​ ​t​o​ ​a​s​k​ ​t​o​ ​j​o​i​n​ ​w​h​i​l​e​ ​I​ ​a​m​ ​i​n​ ​a​ ​c​a​l​l
	 */
	bonjour_accept_call_joins: string
	/**
	 * A​d​d​ ​c​o​n​t​a​c​t
	 */
	bonjour_add_contact: string
	/**
	 * S​e​n​d​ ​r​e​q​u​e​s​t
	 */
	bonjour_send_request: string
	/**
	 * I​n​c​o​m​i​n​g​ ​r​e​q​u​e​s​t​s
	 */
	bonjour_incoming: string
	/**
	 * S​e​n​t​ ​r​e​q​u​e​s​t​s
	 */
	bonjour_outgoing: string
	/**
	 * C​o​n​t​a​c​t​s
	 */
	bonjour_contacts: string
	/**
	 * C​a​l​l
	 */
	bonjour_call: string
	/**
	 * A​s​k​ ​t​o​ ​j​o​i​n
	 */
	bonjour_ask_to_join: string
	/**
	 * A​d​d​ ​t​o​ ​c​a​l​l
	 */
	bonjour_add_to_call: string
	/**
	 * R​e​m​o​v​e
	 */
	bonjour_remove: string
	/**
	 * L​i​s​t​s
	 */
	bonjour_lists: string
	/**
	 * C​r​e​a​t​e​ ​l​i​s​t
	 */
	bonjour_create_list: string
	/**
	 * D​e​l​e​t​e
	 */
	bonjour_delete_list: string
	/**
	 * I​g​n​o​r​e​d
	 */
	bonjour_ignored: string
	/**
	 * I​g​n​o​r​e
	 */
	bonjour_ignore: string
	/**
	 * U​n​-​i​g​n​o​r​e
	 */
	bonjour_unignore: string
	/**
	 * I​n​c​o​m​i​n​g​ ​c​a​l​l
	 */
	bonjour_incoming_call: string
	/**
	 * W​a​n​t​s​ ​t​o​ ​j​o​i​n
	 */
	bonjour_incoming_join: string
	/**
	 * B​o​n​j​o​u​r​ ​r​e​q​u​e​s​t​ ​f​a​i​l​e​d
	 */
	bonjour_error: string
	/**
	 * E​n​a​b​l​e​ ​B​o​n​j​o​u​r​ ​(​o​p​t​i​o​n​a​l​ ​c​o​n​t​a​c​t​s​ ​s​e​r​v​e​r​)
	 */
	bonjour_enabled: string
	/**
	 * W​h​e​n​ ​e​n​a​b​l​e​d​,​ ​t​h​i​s​ ​a​p​p​ ​t​a​l​k​s​ ​t​o​ ​t​h​e​ ​B​o​n​j​o​u​r​ ​s​e​r​v​e​r​ ​y​o​u​ ​c​o​n​f​i​g​u​r​e​.​ ​M​e​d​i​a​ ​a​n​d​ ​M​L​S​ ​k​e​y​s​ ​s​t​a​y​ ​o​n​ ​y​o​u​r​ ​d​e​v​i​c​e​.​ ​O​f​f​ ​b​y​ ​d​e​f​a​u​l​t​.
	 */
	bonjour_enabled_description: string
	/**
	 * B​o​n​j​o​u​r​ ​s​e​r​v​e​r​ ​U​R​L
	 */
	bonjour_server_url: string
	/**
	 * I​n​v​i​t​e​ ​w​i​t​h​ ​a​ ​c​o​d​e
	 */
	bonjour_invites: string
	/**
	 * S​h​a​r​e​ ​a​ ​o​n​e​-​t​i​m​e​ ​c​o​d​e​ ​w​i​t​h​ ​s​o​m​e​o​n​e​ ​u​s​i​n​g​ ​t​h​i​s​ ​s​a​m​e​ ​B​o​n​j​o​u​r​ ​s​e​r​v​e​r​.​ ​S​i​g​n​i​n​g​ ​i​n​ ​i​s​ ​o​p​t​i​o​n​a​l​.
	 */
	bonjour_invites_description: string
	/**
	 * C​r​e​a​t​e​ ​i​n​v​i​t​e
	 */
	bonjour_invite_create: string
	/**
	 * C​o​p​y
	 */
	bonjour_invite_copy: string
	/**
	 * I​n​v​i​t​e​ ​c​o​d​e​ ​c​o​p​i​e​d
	 */
	bonjour_invite_copied: string
	/**
	 * R​e​v​o​k​e
	 */
	bonjour_invite_revoke: string
	/**
	 * J​o​i​n​ ​w​i​t​h​ ​c​o​d​e
	 */
	bonjour_invite_join: string
	/**
	 * I​n​v​i​t​e​ ​c​o​d​e
	 */
	bonjour_invite_code: string
	/**
	 * E​x​p​i​r​e​s
	 */
	bonjour_invite_expires: string
	/**
	 * T​o​o​ ​m​a​n​y​ ​i​n​v​i​t​e​ ​c​o​d​e​s​.​ ​W​a​i​t​ ​a​ ​m​i​n​u​t​e​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	bonjour_invite_rate_limited: string
	/**
	 * T​h​a​t​ ​i​n​v​i​t​e​ ​c​o​d​e​ ​i​s​ ​n​o​t​ ​v​a​l​i​d​.
	 */
	bonjour_invite_invalid: string
	/**
	 * T​h​a​t​ ​i​n​v​i​t​e​ ​c​o​d​e​ ​h​a​s​ ​e​x​p​i​r​e​d​.
	 */
	bonjour_invite_expired: string
	/**
	 * T​h​a​t​ ​i​n​v​i​t​e​ ​c​o​d​e​ ​w​a​s​ ​a​l​r​e​a​d​y​ ​u​s​e​d​.
	 */
	bonjour_invite_used: string
	/**
	 * T​h​a​t​ ​i​n​v​i​t​e​ ​c​o​d​e​ ​w​a​s​ ​r​e​v​o​k​e​d​.
	 */
	bonjour_invite_revoked: string
	/**
	 * Y​o​u​ ​c​a​n​n​o​t​ ​u​s​e​ ​y​o​u​r​ ​o​w​n​ ​i​n​v​i​t​e​ ​c​o​d​e​.
	 */
	bonjour_invite_own: string
	/**
	 * T​h​e​ ​p​e​r​s​o​n​ ​w​h​o​ ​c​r​e​a​t​e​d​ ​t​h​i​s​ ​c​o​d​e​ ​i​s​ ​o​f​f​l​i​n​e​.
	 */
	bonjour_invite_offline: string
	/**
	 * I​n​v​i​t​e​s​ ​a​r​e​ ​n​o​t​ ​r​e​a​d​y​ ​y​e​t​.​ ​T​r​y​ ​a​g​a​i​n​ ​i​n​ ​a​ ​m​o​m​e​n​t​.
	 */
	bonjour_invite_not_ready: string
	/**
	 * C​a​n​n​o​t​ ​a​d​d​ ​s​o​m​e​o​n​e​ ​t​o​ ​t​h​i​s​ ​s​e​s​s​i​o​n​.
	 */
	bonjour_invite_unavailable: string
	/**
	 * L​e​a​v​e​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​s​e​s​s​i​o​n​ ​b​e​f​o​r​e​ ​j​o​i​n​i​n​g​ ​w​i​t​h​ ​a​ ​c​o​d​e​.
	 */
	bonjour_invite_busy: string
	/**
	 * T​h​i​s​ ​s​e​s​s​i​o​n​ ​i​s​ ​f​u​l​l​.
	 */
	bonjour_invite_full: string
	/**
	 * R​e​m​o​t​e​ ​c​o​n​t​r​o​l
	 */
	remote_control: string
	/**
	 * M​o​u​s​e
	 */
	remote_control_mouse: string
	/**
	 * K​e​y​b​o​a​r​d
	 */
	remote_control_keyboard: string
	/**
	 * {​n​a​m​e​}​ ​i​s​ ​r​e​q​u​e​s​t​i​n​g​ ​c​o​n​t​r​o​l
	 * @param {unknown} name
	 */
	remote_control_request: RequiredParams<'name'>
	/**
	 * A​l​l​o​w​ ​m​o​u​s​e
	 */
	remote_control_allow_mouse: string
	/**
	 * A​l​l​o​w​ ​k​e​y​b​o​a​r​d
	 */
	remote_control_allow_keyboard: string
	/**
	 * A​l​l​o​w​ ​b​o​t​h
	 */
	remote_control_allow_both: string
	/**
	 * D​e​n​y
	 */
	remote_control_deny: string
	/**
	 * R​e​m​o​t​e​ ​c​o​n​t​r​o​l​ ​a​c​t​i​v​e
	 */
	remote_control_active: string
	/**
	 * C​o​n​t​r​o​l​l​i​n​g​ ​{​n​a​m​e​}
	 * @param {unknown} name
	 */
	remote_control_controlling: RequiredParams<'name'>
	/**
	 * R​e​m​o​t​e​ ​c​o​n​t​r​o​l​ ​d​i​s​a​b​l​e​d​ ​b​y​ ​h​o​s​t​ ​h​o​t​k​e​y
	 */
	remote_control_emergency: string
	/**
	 * E​m​e​r​g​e​n​c​y​ ​s​t​o​p​:​ ​{​h​o​t​k​e​y​}
	 * @param {unknown} hotkey
	 */
	remote_control_emergency_hotkey: RequiredParams<'hotkey'>
	/**
	 * R​e​m​o​t​e​ ​c​o​n​t​r​o​l​ ​i​s​ ​u​n​a​v​a​i​l​a​b​l​e
	 */
	remote_control_unavailable: string
	/**
	 * T​h​e​ ​e​m​e​r​g​e​n​c​y​ ​s​t​o​p​ ​c​a​n​n​o​t​ ​s​e​e​ ​e​v​e​r​y​ ​k​e​y​b​o​a​r​d​.​ ​I​n​s​t​a​l​l​ ​b​u​i​l​d​/​u​d​e​v​/​7​0​-​p​2​p​-​k​i​w​i​-​i​n​p​u​t​.​r​u​l​e​s​ ​i​n​t​o​ ​/​e​t​c​/​u​d​e​v​/​r​u​l​e​s​.​d​/​,​ ​t​h​e​n​ ​s​i​g​n​ ​i​n​ ​a​g​a​i​n​.
	 */
	remote_control_evdev_permission: string
	/**
	 * A​l​l​o​w​ ​A​c​c​e​s​s​i​b​i​l​i​t​y
	 */
	remote_control_request_permission: string
	/**
	 * A​l​l​o​w​ ​I​n​p​u​t​ ​M​o​n​i​t​o​r​i​n​g
	 */
	remote_control_request_listen: string
	/**
	 * A​p​p​r​o​v​e​ ​p​2​p​.​k​i​w​i​ ​S​i​d​e​c​a​r​ ​(​k​i​w​i​.​p​2​p​.​d​e​s​k​t​o​p​.​s​i​d​e​c​a​r​)​ ​i​n​ ​S​y​s​t​e​m​ ​S​e​t​t​i​n​g​s​.​ ​O​v​e​r​l​a​y​ ​d​r​a​w​i​n​g​ ​d​o​e​s​ ​n​o​t​ ​n​e​e​d​ ​e​i​t​h​e​r​ ​p​e​r​m​i​s​s​i​o​n​.​ ​A​c​c​e​s​s​i​b​i​l​i​t​y​ ​l​e​t​s​ ​t​h​e​ ​h​e​l​p​e​r​ ​t​y​p​e​ ​a​n​d​ ​m​o​v​e​ ​t​h​e​ ​p​o​i​n​t​e​r​.​ ​I​n​p​u​t​ ​M​o​n​i​t​o​r​i​n​g​ ​l​e​t​s​ ​i​t​ ​s​e​e​ ​o​n​l​y​ ​t​h​e​ ​e​m​e​r​g​e​n​c​y​-​s​t​o​p​ ​s​h​o​r​t​c​u​t​.
	 */
	remote_control_permission_helper: string
	/**
	 * I​f​ ​y​o​u​ ​a​l​r​e​a​d​y​ ​a​p​p​r​o​v​e​d​ ​a​c​c​e​s​s​,​ ​q​u​i​t​ ​p​2​p​.​k​i​w​i​ ​a​n​d​ ​o​p​e​n​ ​i​t​ ​a​g​a​i​n​.
	 */
	remote_control_restart_required: string
	/**
	 * O​p​e​n​ ​A​c​c​e​s​s​i​b​i​l​i​t​y​ ​s​e​t​t​i​n​g​s
	 */
	remote_control_open_accessibility: string
	/**
	 * O​p​e​n​ ​I​n​p​u​t​ ​M​o​n​i​t​o​r​i​n​g​ ​s​e​t​t​i​n​g​s
	 */
	remote_control_open_input_monitoring: string
	/**
	 * R​e​c​h​e​c​k​ ​p​e​r​m​i​s​s​i​o​n​s
	 */
	remote_control_recheck: string
	/**
	 * R​e​q​u​e​s​t​ ​c​o​n​t​r​o​l
	 */
	remote_control_request_button: string
}

export type TranslationFunctions = {
	/**
	 * About
	 */
	about: () => LocalizedString
	/**
	 * Advanced
	 */
	advanced: () => LocalizedString
	/**
	 * Basic
	 */
	basic: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Code of conduct
	 */
	code_of_conduct: () => LocalizedString
	/**
	 * Foreground color
	 */
	foreground_color: () => LocalizedString
	/**
	 * Background color
	 */
	background_color: () => LocalizedString
	/**
	 * Connect
	 */
	connect: () => LocalizedString
	/**
	 * Connection established
	 */
	connection_established: () => LocalizedString
	/**
	 * Copy room link
	 */
	copy_my_connection_string: () => LocalizedString
	/**
	 * Disconnect
	 */
	disconnect: () => LocalizedString
	/**
	 * Fullscreen
	 */
	fullscreen: () => LocalizedString
	/**
	 * Exit fullscreen
	 */
	exit_fullscreen: () => LocalizedString
	/**
	 * Host a session
	 */
	host_a_session: () => LocalizedString
	/**
	 * Room link
	 */
	host_connection_string: () => LocalizedString
	/**
	 * Room server (HTTPS)
	 */
	room_server_url: () => LocalizedString
	/**
	 * Waiting for the host to connect…
	 */
	waiting_for_host: () => LocalizedString
	/**
	 * Hosting a session
	 */
	hosting_a_session: () => LocalizedString
	/**
	 * Is microphone active on connect
	 */
	is_microphone_active_on_connect: () => LocalizedString
	/**
	 * Join a session
	 */
	join_a_session: () => LocalizedString
	/**
	 * Joined a session
	 */
	joined_a_session: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Choose your preferred language (after changing the language, you need to restart the app)
	 */
	language_description: () => LocalizedString
	/**
	 * Media
	 */
	media: () => LocalizedString
	/**
	 * Microphone active
	 */
	microphone_active: () => LocalizedString
	/**
	 * Microphone inactive
	 */
	microphone_inactive: () => LocalizedString
	/**
	 * No screens were found to share
	 */
	no_screens_found: () => LocalizedString
	/**
	 * Not streaming your display
	 */
	not_streaming_your_display: () => LocalizedString
	/**
	 * Participant connection string
	 */
	participant_connection_string: () => LocalizedString
	/**
	 * Privacy policy
	 */
	privacty_policy: () => LocalizedString
	/**
	 * Remote cursors disabled
	 */
	remote_cursors_disabled: () => LocalizedString
	/**
	 * Remote cursors enabled
	 */
	remote_cursors_enabled: () => LocalizedString
	/**
	 * Cursors and remote mouse are only available when sharing the full screen.
	 */
	fullscreen_pointer_only: () => LocalizedString
	/**
	 * Remote screen
	 */
	remote_screen: () => LocalizedString
	/**
	 * Report a bug
	 */
	report_a_bug: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Could not start screen sharing
	 */
	screen_share_failed: () => LocalizedString
	/**
	 * Screens
	 */
	screens: () => LocalizedString
	/**
	 * Search
	 */
	search: () => LocalizedString
	/**
	 * See the code
	 */
	see_the_code: () => LocalizedString
	/**
	 * Share
	 */
	share: () => LocalizedString
	/**
	 * Share your screen
	 */
	share_your_screen: () => LocalizedString
	/**
	 * Session started
	 */
	session_started: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Shoulders of giants
	 */
	shoulders_of_giants: () => LocalizedString
	/**
	 * p2p.kiwi Screen Sharing is built on top of the following open-source projects (in no particular order)
	 */
	shoulders_of_giants_description: () => LocalizedString
	/**
	 * Start a new session
	 */
	start_a_new_session: () => LocalizedString
	start_without_sharing: () => LocalizedString
	/**
	 * Streaming your display
	 */
	streaming_your_display: () => LocalizedString
	/**
	 * STUN/TURN Server Objects (separated by new lines)
	 */
	stun_turn_server_objects: () => LocalizedString
	/**
	 * Terms of service
	 */
	terms_of_service: () => LocalizedString
	/**
	 * Username
	 */
	username: () => LocalizedString
	/**
	 * Website
	 */
	website: () => LocalizedString
	/**
	 * Windows
	 */
	windows: () => LocalizedString
	/**
	 * Zoom in
	 */
	zoom_in: () => LocalizedString
	/**
	 * Zoom out
	 */
	zoom_out: () => LocalizedString
	/**
	 * Approve
	 */
	approve: () => LocalizedString
	/**
	 * Change screen
	 */
	change_screen: () => LocalizedString
	/**
	 * Connection closed
	 */
	connection_closed: () => LocalizedString
	/**
	 * Connection failed
	 */
	connection_failed: () => LocalizedString
	/**
	 * This connection string is missing its encryption invite. Paste the full text, including everything after #.
	 */
	connection_invite_missing: () => LocalizedString
	/**
	 * The STUN or TURN server rejected the login for {url} (code {code}). Check the username and password in Settings.
	 */
	connection_ice_auth: (arg: { code: unknown, url: unknown }) => LocalizedString
	/**
	 * Could not reach the STUN or TURN server {url} (code {code}).
	 */
	connection_ice_unreachable: (arg: { code: unknown, url: unknown }) => LocalizedString
	/**
	 * Could not reach the TCP TURN server {url} (code {code}).
	 */
	connection_ice_tcp_unreachable: (arg: { code: unknown, url: unknown }) => LocalizedString
	/**
	 * Address gathering timed out before a public or relay address appeared. Check the STUN server in Settings, or add a TURN server.
	 */
	connection_ice_gathering_timeout: () => LocalizedString
	/**
	 * Only a local address was found. STUN did not provide a public address, so these peers cannot reach each other across networks. Check the STUN server in Settings, or add a TURN server.
	 */
	connection_ice_host_only: () => LocalizedString
	/**
	 * A public address was found, but the connection checks still failed. A symmetric NAT usually needs a TURN server in Settings.
	 */
	connection_ice_need_turn: () => LocalizedString
	/**
	 * A TURN relay address was found, but the connection checks still failed.
	 */
	connection_ice_relay_failed: () => LocalizedString
	/**
	 * No network addresses were gathered. Check the STUN and TURN servers in Settings.
	 */
	connection_ice_no_candidates: () => LocalizedString
	/**
	 * The WebRTC connection checks failed before a peer was reached.
	 */
	connection_ice_unknown: () => LocalizedString
	/**
	 * Coordinator
	 */
	coordinator: () => LocalizedString
	/**
	 * Deny
	 */
	deny: () => LocalizedString
	/**
	 * Dismiss
	 */
	dismiss: () => LocalizedString
	/**
	 * End session
	 */
	end_session: () => LocalizedString
	/**
	 * Everyone else has left
	 */
	everyone_else_has_left: () => LocalizedString
	/**
	 * The host has ended the session
	 */
	host_ended_the_session: () => LocalizedString
	/**
	 * Invite another participant
	 */
	invite_another: () => LocalizedString
	/**
	 * Leave
	 */
	leave: () => LocalizedString
	/**
	 * People in this session
	 */
	peer_list: () => LocalizedString
	/**
	 * Presenter
	 */
	presenter: () => LocalizedString
	/**
	 * The presenter has left
	 */
	presenter_left: () => LocalizedString
	/**
	 * Request to present
	 */
	request_to_present: () => LocalizedString
	/**
	 * This session is full
	 */
	room_is_full: () => LocalizedString
	/**
	 * {name} wants to become the presenter
	 */
	vote_in_progress: (arg: { name: unknown }) => LocalizedString
	/**
	 * Presenter request was declined
	 */
	vote_rejected: () => LocalizedString
	/**
	 * Please wait a moment before requesting to present again
	 */
	vote_cooldown: () => LocalizedString
	/**
	 * Remove from session
	 */
	remove_from_session: () => LocalizedString
	/**
	 * Remove {name} from the session?
	 */
	vote_remove: (arg: { name: unknown }) => LocalizedString
	/**
	 * The group is voting to remove you from the session
	 */
	vote_removing_you: () => LocalizedString
	/**
	 * You were removed from the session
	 */
	removed_from_session: () => LocalizedString
	/**
	 * Removal was declined
	 */
	vote_remove_rejected: () => LocalizedString
	/**
	 * Please wait a moment before starting another vote
	 */
	vote_remove_cooldown: () => LocalizedString
	/**
	 * You
	 */
	you: () => LocalizedString
	/**
	 * Hardware video acceleration (VA-API)
	 */
	hardware_video_acceleration: () => LocalizedString
	/**
	 * Use the GPU to encode and decode video. Turn this off if screen sharing is black or crashes. Restart the app after changing.
	 */
	hardware_video_acceleration_description: () => LocalizedString
	/**
	 * Camera
	 */
	camera: () => LocalizedString
	/**
	 * Camera on
	 */
	camera_on: () => LocalizedString
	/**
	 * Camera off
	 */
	camera_off: () => LocalizedString
	/**
	 * Chat
	 */
	chat: () => LocalizedString
	/**
	 * Message
	 */
	chat_placeholder: () => LocalizedString
	/**
	 * Send
	 */
	send: () => LocalizedString
	/**
	 * Debug
	 */
	debug: () => LocalizedString
	/**
	 * Enable debug logs
	 */
	debug_logs: () => LocalizedString
	/**
	 * Show a Debug page with connection and WebRTC logs. Turn this on before reproducing a problem, then copy the log.
	 */
	debug_logs_description: () => LocalizedString
	/**
	 * Clear log
	 */
	debug_clear: () => LocalizedString
	/**
	 * Copy log
	 */
	debug_copy: () => LocalizedString
	/**
	 * No debug log entries yet. Reproduce the issue, then copy the log.
	 */
	debug_empty: () => LocalizedString
	/**
	 * Camera
	 */
	camera_device: () => LocalizedString
	/**
	 * Microphone
	 */
	microphone_device: () => LocalizedString
	/**
	 * System default
	 */
	default_media_device: () => LocalizedString
	/**
	 * End-to-end encryption
	 */
	e2ee_enabled: () => LocalizedString
	/**
	 * Protect chat, votes, cursors, and media with MLS. If encryption cannot be established, traffic is dropped instead of sent in plaintext.
	 */
	e2ee_enabled_description: () => LocalizedString
	/**
	 * Encrypt media (SFrame)
	 */
	media_e2ee: () => LocalizedString
	/**
	 * Required while end-to-end encryption is on. Screen, camera, and microphone never fall back to plaintext.
	 */
	media_e2ee_description: () => LocalizedString
	/**
	 * End-to-end encrypted
	 */
	e2ee_on: () => LocalizedString
	/**
	 * Encryption is required; media is held until SFrame is ready
	 */
	e2ee_app_only: () => LocalizedString
	/**
	 * Not end-to-end encrypted
	 */
	e2ee_off: () => LocalizedString
	/**
	 * Encryption
	 */
	e2ee_status: () => LocalizedString
	/**
	 * Compare this security code and fingerprints with the other people in the session.
	 */
	verification: () => LocalizedString
	/**
	 * Security code
	 */
	verification_code: () => LocalizedString
	/**
	 * A peer identity changed during this session
	 */
	identity_changed: () => LocalizedString
	/**
	 * Bonjour
	 */
	bonjour: () => LocalizedString
	/**
	 * Sign in
	 */
	bonjour_sign_in: () => LocalizedString
	/**
	 * Sign out
	 */
	bonjour_sign_out: () => LocalizedString
	/**
	 * Bonjour is optional. Sign in with SSO on your configured server to add contacts and place calls without exchanging kiwi:// links.
	 */
	bonjour_sign_in_description: () => LocalizedString
	/**
	 * Choose a unique username so others can add you.
	 */
	bonjour_choose_username: () => LocalizedString
	/**
	 * Accept contact requests (time-limited)
	 */
	bonjour_accept_requests: () => LocalizedString
	/**
	 * Allow contacts to ask to join while I am in a call
	 */
	bonjour_accept_call_joins: () => LocalizedString
	/**
	 * Add contact
	 */
	bonjour_add_contact: () => LocalizedString
	/**
	 * Send request
	 */
	bonjour_send_request: () => LocalizedString
	/**
	 * Incoming requests
	 */
	bonjour_incoming: () => LocalizedString
	/**
	 * Sent requests
	 */
	bonjour_outgoing: () => LocalizedString
	/**
	 * Contacts
	 */
	bonjour_contacts: () => LocalizedString
	/**
	 * Call
	 */
	bonjour_call: () => LocalizedString
	/**
	 * Ask to join
	 */
	bonjour_ask_to_join: () => LocalizedString
	/**
	 * Add to call
	 */
	bonjour_add_to_call: () => LocalizedString
	/**
	 * Remove
	 */
	bonjour_remove: () => LocalizedString
	/**
	 * Lists
	 */
	bonjour_lists: () => LocalizedString
	/**
	 * Create list
	 */
	bonjour_create_list: () => LocalizedString
	/**
	 * Delete
	 */
	bonjour_delete_list: () => LocalizedString
	/**
	 * Ignored
	 */
	bonjour_ignored: () => LocalizedString
	/**
	 * Ignore
	 */
	bonjour_ignore: () => LocalizedString
	/**
	 * Un-ignore
	 */
	bonjour_unignore: () => LocalizedString
	/**
	 * Incoming call
	 */
	bonjour_incoming_call: () => LocalizedString
	/**
	 * Wants to join
	 */
	bonjour_incoming_join: () => LocalizedString
	/**
	 * Bonjour request failed
	 */
	bonjour_error: () => LocalizedString
	/**
	 * Enable Bonjour (optional contacts server)
	 */
	bonjour_enabled: () => LocalizedString
	/**
	 * When enabled, this app talks to the Bonjour server you configure. Media and MLS keys stay on your device. Off by default.
	 */
	bonjour_enabled_description: () => LocalizedString
	/**
	 * Bonjour server URL
	 */
	bonjour_server_url: () => LocalizedString
	/**
	 * Invite with a code
	 */
	bonjour_invites: () => LocalizedString
	/**
	 * Share a one-time code with someone using this same Bonjour server. Signing in is optional.
	 */
	bonjour_invites_description: () => LocalizedString
	/**
	 * Create invite
	 */
	bonjour_invite_create: () => LocalizedString
	/**
	 * Copy
	 */
	bonjour_invite_copy: () => LocalizedString
	/**
	 * Invite code copied
	 */
	bonjour_invite_copied: () => LocalizedString
	/**
	 * Revoke
	 */
	bonjour_invite_revoke: () => LocalizedString
	/**
	 * Join with code
	 */
	bonjour_invite_join: () => LocalizedString
	/**
	 * Invite code
	 */
	bonjour_invite_code: () => LocalizedString
	/**
	 * Expires
	 */
	bonjour_invite_expires: () => LocalizedString
	/**
	 * Too many invite codes. Wait a minute and try again.
	 */
	bonjour_invite_rate_limited: () => LocalizedString
	/**
	 * That invite code is not valid.
	 */
	bonjour_invite_invalid: () => LocalizedString
	/**
	 * That invite code has expired.
	 */
	bonjour_invite_expired: () => LocalizedString
	/**
	 * That invite code was already used.
	 */
	bonjour_invite_used: () => LocalizedString
	/**
	 * That invite code was revoked.
	 */
	bonjour_invite_revoked: () => LocalizedString
	/**
	 * You cannot use your own invite code.
	 */
	bonjour_invite_own: () => LocalizedString
	/**
	 * The person who created this code is offline.
	 */
	bonjour_invite_offline: () => LocalizedString
	/**
	 * Invites are not ready yet. Try again in a moment.
	 */
	bonjour_invite_not_ready: () => LocalizedString
	/**
	 * Cannot add someone to this session.
	 */
	bonjour_invite_unavailable: () => LocalizedString
	/**
	 * Leave the current session before joining with a code.
	 */
	bonjour_invite_busy: () => LocalizedString
	/**
	 * This session is full.
	 */
	bonjour_invite_full: () => LocalizedString
	/**
	 * Remote control
	 */
	remote_control: () => LocalizedString
	/**
	 * Mouse
	 */
	remote_control_mouse: () => LocalizedString
	/**
	 * Keyboard
	 */
	remote_control_keyboard: () => LocalizedString
	/**
	 * {name} is requesting control
	 */
	remote_control_request: (arg: { name: unknown }) => LocalizedString
	/**
	 * Allow mouse
	 */
	remote_control_allow_mouse: () => LocalizedString
	/**
	 * Allow keyboard
	 */
	remote_control_allow_keyboard: () => LocalizedString
	/**
	 * Allow both
	 */
	remote_control_allow_both: () => LocalizedString
	/**
	 * Deny
	 */
	remote_control_deny: () => LocalizedString
	/**
	 * Remote control active
	 */
	remote_control_active: () => LocalizedString
	/**
	 * Controlling {name}
	 */
	remote_control_controlling: (arg: { name: unknown }) => LocalizedString
	/**
	 * Remote control disabled by host hotkey
	 */
	remote_control_emergency: () => LocalizedString
	/**
	 * Emergency stop: {hotkey}
	 */
	remote_control_emergency_hotkey: (arg: { hotkey: unknown }) => LocalizedString
	/**
	 * Remote control is unavailable
	 */
	remote_control_unavailable: () => LocalizedString
	/**
	 * The emergency stop cannot see every keyboard. Install build/udev/70-p2p-kiwi-input.rules into /etc/udev/rules.d/, then sign in again.
	 */
	remote_control_evdev_permission: () => LocalizedString
	/**
	 * Allow Accessibility
	 */
	remote_control_request_permission: () => LocalizedString
	/**
	 * Allow Input Monitoring
	 */
	remote_control_request_listen: () => LocalizedString
	/**
	 * Approve p2p.kiwi Sidecar (kiwi.p2p.desktop.sidecar) in System Settings. Overlay drawing does not need either permission. Accessibility lets the helper type and move the pointer. Input Monitoring lets it see only the emergency-stop shortcut.
	 */
	remote_control_permission_helper: () => LocalizedString
	/**
	 * If you already approved access, quit p2p.kiwi and open it again.
	 */
	remote_control_restart_required: () => LocalizedString
	/**
	 * Open Accessibility settings
	 */
	remote_control_open_accessibility: () => LocalizedString
	/**
	 * Open Input Monitoring settings
	 */
	remote_control_open_input_monitoring: () => LocalizedString
	/**
	 * Recheck permissions
	 */
	remote_control_recheck: () => LocalizedString
	/**
	 * Request control
	 */
	remote_control_request_button: () => LocalizedString
}

export type Formatters = {}
