export const DOWNLOAD_BASE_URL = 'https://github.com/whoslucaxs/a.webo/releases/latest/download/'
export const RELEASES_URL = 'https://github.com/whoslucaxs/a.webo/releases'

export const DOWNLOAD_URLS = {
  RELEASES: RELEASES_URL,
  WINDOWS_X64_INSTALLER: `${DOWNLOAD_BASE_URL}a-webo-setup_x64.exe`,
  WINDOWS_X64_PORTABLE: `${DOWNLOAD_BASE_URL}a-webo-portable_x64.exe`,
  LINUX_APPIMAGE_X86_64: `${DOWNLOAD_BASE_URL}a-webo_x86_64.AppImage`,
  LINUX_APPIMAGE_ARM64: RELEASES_URL,
  LINUX_DEB_AMD64: RELEASES_URL,
  LINUX_DEB_ARM64: RELEASES_URL,
  LINUX_FLATPAK_X86_64: RELEASES_URL,
  LINUX_FLATPAK_AARCH64: RELEASES_URL,
  LINUX_SNAP_AMD64: RELEASES_URL,
  MACOS_UNIVERSAL_DMG: RELEASES_URL,
  WINDOWS_STORE: RELEASES_URL,
} as const
