---
name: Build on Windows

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        shell: bash
        run: |
          echo "VERSION=1.0.0" >> $GITHUB_ENV
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          env: true
          export_path: true
      - name: Install make
        run: choco install make --no-progress --yes
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Windows
        shell: bash
        run: |
          ODIN_ROOT="$(cygpath -u "$(mise where odin)")"
          export ODIN="$ODIN_ROOT/odin.exe"
          export PATH="$ODIN_ROOT:$PATH"
          make windows
        env:
          VERSION: ${{ env.VERSION }}
