---
name: Build Linux x64

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          echo "VERSION=1.0.0" >> $GITHUB_ENV
      - name: Install OS packages
        run: |
          sudo apt update && \
          sudo apt-get install -y flatpak flatpak-builder libx11-dev \
            libxfixes-dev libxext-dev libxrandr-dev libxtst-dev \
            libwayland-dev wayland-protocols unzip && \
          sudo snap install snapcraft --classic && \
          flatpak remote-add \
            --user \
            --if-not-exists \
            flathub https://flathub.org/repo/flathub.flatpakrepo
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          env: true
          export_path: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Linux
        run: make linux
        env:
          VERSION: ${{ env.VERSION }}
