---
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Install OS packages
        run: |
          sudo apt update && \
          sudo apt-get install -y flatpak flatpak-builder libx11-dev \
            libxfixes-dev libxext-dev libxrandr-dev libxtst-dev \
            libwayland-dev wayland-protocols unzip && \
          sudo snap install snapcraft --classic && \
          flatpak remote-add \
            --user \
            --if-not-exists \
            flathub https://flathub.org/repo/flathub.flatpakrepo
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          env: true
          export_path: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Linux
        run: make linux
        env:
          VERSION: ${{ env.VERSION }}
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            dist/p2p-kiwi_amd64.deb
            dist/p2p-kiwi_amd64.snap
            dist/p2p-kiwi_x86_64.AppImage
            dist/p2p-kiwi_x86_64.flatpak
          if-no-files-found: error
  build-linux-arm64:
    name: Build Linux ARM64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Install OS packages
        run: |
          sudo apt update && \
          sudo apt-get install -y flatpak flatpak-builder && \
          flatpak remote-add \
            --user \
            --if-not-exists \
            flathub https://flathub.org/repo/flathub.flatpakrepo
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          env: true
          export_path: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Linux ARM64
        run: make linux-arm64
        env:
          VERSION: ${{ env.VERSION }}
      - name: Upload Linux ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: |
            dist/p2p-kiwi_arm64.deb
            dist/p2p-kiwi_arm64.AppImage
            dist/p2p-kiwi_aarch64.flatpak
          if-no-files-found: error
  # deploy-aur:
  #   name: Deploy to AUR
  #   needs: publish-release
  #   runs-on: ubuntu-latest
  #   container:
  #     # INFO:  Use Arch image to access updpkgsums
  #     image: archlinux:latest
  #   steps:
  #     - name: Install dependencies
  #       run: pacman -Syu --noconfirm pacman-contrib git openssh
  #     - uses: actions/checkout@v5
  #     - name: Update Version in PKGBUILD
  #       run: |
  #         VERSION=${{ github.ref_name }}
  #         VERSION_NO_V=${VERSION#v}
  #         echo "CLEAN_VERSION=$VERSION_NO_V" >> $GITHUB_ENV
  #         sed -i "s/pkgver=.*/pkgver=$VERSION_NO_V/" ./scripts/PKGBUILD
  #     - name: Publish to AUR
  #       uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
  #       with:
  #         pkgname: p2p-kiwi-bin
  #         pkgbuild: ./scripts/PKGBUILD
  #         commit_username: ${{ secrets.AUR_USERNAME }}
  #         commit_email: ${{ secrets.AUR_EMAIL }}
  #         ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
  #         commit_message: 'Update to v${{ env.CLEAN_VERSION }}'
  #         updpkgsums: true
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          env: true
          export_path: true
      - name: Install make
        run: choco install make --no-progress --yes
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Windows
        shell: bash
        run: |
          ODIN_ROOT="$(cygpath -u "$(mise where odin)")"
          export ODIN="$ODIN_ROOT/odin.exe"
          export PATH="$ODIN_ROOT:$PATH"
          make windows
        env:
          VERSION: ${{ env.VERSION }}
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/p2p-kiwi-setup_x64.exe
          if-no-files-found: error
  build-macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          env: true
          export_path: true
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install the Apple certificate and API key
        id: keychain
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}
          AUTH_KEY_BASE64: ${{ secrets.APPLE_AUTH_KEY_BASE64 }}
        run: ./scripts/ci-import-apple-certs.sh
      - name: Build MacOS
        env:
          VERSION: ${{ env.VERSION }}
          CODESIGNING_IDENTITY: ${{ secrets.APPLE_CODESIGNING_IDENTITY }}
        run: |
          export CSC_NAME=$(base64 --decode <<< "$CODESIGNING_IDENTITY")
          make macos
      - name: Notarize macOS DMG
        env:
          AUTH_KEY_PATH: ${{ steps.keychain.outputs.auth_key_path }}
          KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          ISSUER: ${{ secrets.APPLE_ISSUER }}
        run: |
          export KEY_ID=$(base64 --decode <<< "$KEY_ID")
          export ISSUER=$(base64 --decode <<< "$ISSUER")
          ./scripts/ci-notarize-macos.sh
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: dist/p2p-kiwi_universal.dmg
          if-no-files-found: error
  publish-release:
    name: Publish GitHub Release
    needs:
      - build-linux
      - build-linux-arm64
      - build-windows
      - build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up env
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Publish release with all artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: ./scripts/release.sh
